Workflow created
Uni-Sopron/szta-22t-azul-tileguys pull request #7
Opened 2022-03-05 15:10 UTC by TukovitsBalazs

2022-03-07 19:15 UTC, oliverosz requested changes

2022-03-07 19:15 UTC, oliverosz commented on .github/workflows/gradle.yml
> +    branches: [master]
Ne legyen branch filter, minden branchen fusson le a push eventre.

2022-03-07 20:11 UTC, TukovitsBalazs commented on .github/workflows/gradle.yml
> +    branches: [master]
Revoled

2022-06-13 07:41 UTC, oliverosz commented
Még mindig failel a build.

2022-06-13 15:12 UTC, wtomee commented
Érdekes, a következő hibakóddal failel:
This request was automatically failed because there were no enabled runners online to process the request for more than 1 day

Amikor hibás volt a yaml fájlban valami, akkor eddig sem jutott el.

2022-06-13 15:44 UTC, wtomee commented
Zárom ezt a merge requestet és a másik maven workflowra indítok egyet, az működik.

2022-06-13 15:44 UTC, closed without merging